// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lorqwrykuadjcvtpqfvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvcnF3cnlrdWFkamN2dHBxZnZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODczNDYsImV4cCI6MjA2NTU2MzM0Nn0.iIpS-aWYlVL1o0JM8GKxC11ntVVjfqN9yvyhpIRR8d8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);